import { createStore } from 'vuex'

export default createStore({
    state: {
		userInfo:{
			'id':'1',
			'img': '../static/img/avator.png',
			'name':'我就是我 不一样的烟火'
		},//用户信息
		totalData: {
			total_day: 0,
			total_number: 0,
			last_time: '',
			notes: 1
		},//个人中心数据信息
		token:'',
		http:'http://billserver/',
		dbList:[],//数据表集合
		payList:[
			{
				id:1,
				imgUrl:'../../static/img/default1.png',
				name:'默认',
				type:'1'
			},
			{
				id:2,
				imgUrl:'../../static/img/moring1.png',
				name:'早餐',
				type:'1'
			},
			{
				id:3,
				imgUrl:'../../static/img/afternoon1.png',
				name:'午餐',
				type:'1'
			},
			{
				id:4,
				imgUrl:'../../static/img/eventing1.png',
				name:'晚餐',
				type:'1'
			},
			{
				id:5,
				imgUrl:'../../static/img/snacks1.png',
				name:'零食',
				type:'1'
			},
			{
				id:6,
				imgUrl:'../../static/img/dringks1.png',
				name:'饮料',
				type:'1'
			},
			{
				id:7,
				imgUrl:'../../static/img/education1.png',
				name:'教育',
				type:'1'
			},
			{
				id:8,
				imgUrl:'../../static/img/entertainment1.png',
				name:'娱乐',
				type:'1'
			},
			{
				id:9,
				imgUrl:'../../static/img/hongbao1.png',
				name:'红包',
				type:'1'
			},
			{
				id:10,
				imgUrl:'../../static/img/Fruits1.png',
				name:'水果',
				type:'1'
			},
			{
				id:11,
				imgUrl:'../../static/img/cosmetology1.png',
				name:'美容美甲',
				type:'1',
			},
			{
				id:12,
				imgUrl:'../../static/img/jiaotong1.png',
				name:'交通',
				type:'1'
			},
			{
				id:13,
				imgUrl:'../../static/img/life1.png',
				name:'生活用品',
				type:'1'
			},
			{
				id:14,
				imgUrl:'../../static/img/study1.png',
				name:'学习',
				type:'1'
			},
			{
				id:15,
				imgUrl:'../../static/img/Vegetables1.png',
				name:'买菜',
				type:'1'
			},
			{
				id:16,
				imgUrl:'../../static/img/yiyao1.png',
				name:'医药',
				type:'1'
			},
			{
				id:17,
				imgUrl:'../../static/img/taobao1.png',
				name:'淘宝',
				type:'1'
			},
			{
				id:18,
				imgUrl:'../../static/img/house1.png',
				name:'房租',
				type:'1'
			},
			{
				id:19,
				imgUrl:'../../static/img/iphone1.png',
				name:'话费',
				type:'1'
			},
			{
				id:20,
				imgUrl:'../../static/img/Digital1.png',
				name:'数码',
				type:'1'
			},
			{
				id:21,
				imgUrl:'../../static/img/water1.png',
				name:'水费',
				type:'1'
			},
			{
				id:22,
				imgUrl:'../../static/img/electric1.png',
				name:'电费',
				type:'1'
			},
			{
				id:23,
				imgUrl:'../../static/img/mortgage1.png',
				name:'房贷',
				type:'1'
			},
			{
				id:24,
				imgUrl:'../../static/img/weixin1.png',
				name:'微信',
				type:'1'
			},
			{
				id:25,
				imgUrl:'../../static/img/zhi1.png',
				name:'支付宝',
				type:'1'
			},
			{
				id:26,
				imgUrl:'../../static/img/work1.png',
				name:'办公用品',
				type:'1'
			},
			{
				id:27,
				imgUrl:'../../static/img/cmyy1.png',
				name:'柴米油盐',
				type:'1'
			},
			{
				id:28,
				imgUrl:'../../static/img/jiaju1.png',
				name:'家具用品',
				type:'1'
			},
			{
				id:29,
				imgUrl:'../../static/img/rose1.png',
				name:'服饰鞋帽',
				type:'1'
			},
			{
				id:30,
				imgUrl:'../../static/img/mian1.png',
				name:'谷物粮面',
				type:'1'
			},
			{
				id:31,
				imgUrl:'../../static/img/Travel1.png',
				name:'旅游',
				type:'1'
			},
			{
				id:32,
				imgUrl:'../../static/img/express1.png',
				name:'快递',
				type:'1'
			},
			{
				id:33,
				imgUrl:'../../static/img/tv1.png',
				name:'家用电器',
				type:'1'
			},
		],
		incomeList:[
			{
				id:1,
				imgUrl:'../../static/img/cunqianguan.png',
				name:'其他收入',
				type:'2'
			},{
				id:2,
				imgUrl:'../../static/img/gongzi.png',
				name:'工资',
				type:'2'
			},{
				id:3,
				imgUrl:'../../static/img/licai.png',
				name:'理财',
				type:'2'
			},{
				id:4,
				imgUrl:'../../static/img/hongbao1.png',
				name:'红包',
				type:'2'
			},{
				id:5,
				imgUrl:'../../static/img/shangye.png',
				name:'营业收入',
				type:'2'
			},{
				id:6,
				imgUrl:'../../static/img/jianzhi.png',
				name:'兼职外快',
				type:'2'
			},
		],
    },
    mutations: {
        
    }
})
